services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/log/echelon:/app/Logs
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=Production
      - Logging__Settings__Directory=/app/Logs 